module PythonTypes 
type ClassName = string 
type FieldName = string 
type EnumName = FieldName 
type EnumOptions = string list 
type MethodName = FieldName 
let Main___class__ : ClassName*FieldName = "Main","__class__" 
let Main___delattr__ : ClassName*FieldName = "Main","__delattr__" 
let Main___dict__ : ClassName*FieldName = "Main","__dict__" 
let Main___dir__ : ClassName*FieldName = "Main","__dir__" 
let Main___doc__ : ClassName*FieldName = "Main","__doc__" 
let Main___eq__ : ClassName*FieldName = "Main","__eq__" 
let Main___format__ : ClassName*FieldName = "Main","__format__" 
let Main___ge__ : ClassName*FieldName = "Main","__ge__" 
let Main___getattribute__ : ClassName*FieldName = "Main","__getattribute__" 
let Main___gt__ : ClassName*FieldName = "Main","__gt__" 
let Main___hash__ : ClassName*FieldName = "Main","__hash__" 
let Main___init__ : ClassName*MethodName = "Main","__init__" 
let Main___init_subclass__ : ClassName*FieldName = "Main","__init_subclass__" 
let Main___le__ : ClassName*FieldName = "Main","__le__" 
let Main___lt__ : ClassName*FieldName = "Main","__lt__" 
let Main___module__ : ClassName*FieldName = "Main","__module__" 
let Main___ne__ : ClassName*FieldName = "Main","__ne__" 
let Main___new__ : ClassName*FieldName = "Main","__new__" 
let Main___reduce__ : ClassName*FieldName = "Main","__reduce__" 
let Main___reduce_ex__ : ClassName*FieldName = "Main","__reduce_ex__" 
let Main___repr__ : ClassName*FieldName = "Main","__repr__" 
let Main___setattr__ : ClassName*FieldName = "Main","__setattr__" 
let Main___sizeof__ : ClassName*FieldName = "Main","__sizeof__" 
let Main___str__ : ClassName*FieldName = "Main","__str__" 
let Main___subclasshook__ : ClassName*FieldName = "Main","__subclasshook__" 
let Main___weakref__ : ClassName*FieldName = "Main","__weakref__" 
let Main_t_onset : ClassName*FieldName = "Main","t_onset" 
